modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory (28 is current forge version)
license= "${mod_license}"
issueTrackerURL="https://github.com/ModMCdl/EndgameExtension/issues" #optional
[[mods]] #mandatory
modId="endgameextension" #mandatory
version="${mod_version}" #mandatory
displayName="Endgame Extension" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/endgame-extension-mod" #optional
logoFile="endgameextension_logo.png" #optional
credits="Thanks for this mod goes to modmcdl for making the 1.12.2 version" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''
# Base Forge
[[dependencies.endgameextension]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
# Base Minecraft
[[dependencies.endgameextension]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"